### ISSUE TITLE
Status line is modified by the padding buffers

### ISSUE THREAD

**Issue by uraza** [shortcuts/no-neck-pain.nvim#147]
Hi.

Thanks for developing this great plugin, it is very helpful.

## Description

When turning on NoNeckPain, the status line is modified by the padding buffers.

## Steps to reproduce

I use NoNeckPain without any custom configuration, I do not have any status line plugin either.

Before enabling NoNeckPain, the status line at the bottom of Neovim looks like this:

![image](https://user-images.githubusercontent.com/3456223/213744140-6db31186-0a32-47fd-b3b0-237959d80050.png)

After enabling NoNeckPain, the status line is modified by the padding buffers like this (its's like each buffer has its own status line information):

![image](https://user-images.githubusercontent.com/3456223/213744037-e5e6112d-f8f9-4d5b-aad6-541e50bab904.png)

## Expected behavior

Ideally I would like the status line to remain unchanged (single status line across all the screen).
I am not sure if this is possible using Neovim's default status line (if I am not mistaken, the showcase uses some status line plugin like lualine).

Thanks.

**Comment by shortcuts** [comment]
Hey! Thanks for the feedback, hope you like the plugin :)

> Ideally I would like the status line to remain unchanged (single status line across all the screen).

The plugin creates empty side buffers to provide this padding logic, which result in the correct behavior of the status-line when configured per-buffer.

> I am not sure if this is possible using Neovim's default status line

Since https://github.com/neovim/neovim/pull/17266, you can use the global status line to only display it for the active window

------

Closing this issue as the plugin can't do anything about it, feel free to reopen if you feel like it's needed!

**Comment by uraza** [comment]
Thanks for the info about the global status line capability, I will have a look at it.
Have a great day!

**Comment by shortcuts** [comment]
> Thanks for the info about the global status line capability, I will have a look at it. Have a great day!

Thanks, you too :)

**Comment by nivethan-me** [comment]
the global status line fixed this issue for me

include this in your config lua file
`vim.opt.laststatus=3`
