### ISSUE TITLE
Neotree causes NNP to exit when launched, if there is no right buffer

### ISSUE THREAD

**Issue by acurrieclark** [shortcuts/no-neck-pain.nvim#236]
## Description

To start, I just want to say how much I love this plugin. I have been looking for a "zen mode" style plugin which doesn't move when the file explorer is open **forever**.

In my dream setup, I would be able to fix the width of the left buffer, so that the tree floated on top of it (as it is now). That way if I added a pane to the right of the editor, everything would hopefully stay exactly where it is.

I wondered if removing the right buffer might help, but it seems that now whenever I open NeoTree, the left buffer just disappears.

## Steps to reproduce

Plugin setup
```lua
return {
  "shortcuts/no-neck-pain.nvim",
  version = '*',
  config = function()
    require("no-neck-pain").setup({
      width = 120,
      buffers = {
        right = {
          enabled = false,
        },
        wo = {
          fillchars = 'eob: '
        }
      },
      integrations = {
        NeoTree = {
          reopen = false
        }
      }
    });
  end
}
```

Open a file in NNP mode, then open NeoTree.

## Expected behavior

NeoTree would appear, and the editor buffer would stay in place.

## Environment

- Neovim version: 0.9.1
- no-neck-pain.nvim version: 1.2.3

**Comment by shortcuts** [comment]
> To start, I just want to say how much I love this plugin. I have been looking for a "zen mode" style plugin which doesn't move when the file explorer is open forever.

💓 thanks for the feedback and the love!

>  it seems that now whenever I open NeoTree, the left buffer just disappears.

Would you mind sharing a screen recording of the behaviour? Just so I can make sure I reproduce exactly the same issue

----

I don't know how big your screen is, but in case there's "just enough space" for the NNP buffers, Neotree and your work buffers, it's possible that the issue comes from `minSideBufferWidth` (see [configuration](https://github.com/shortcuts/no-neck-pain.nvim#-configuration)), which basically prevents NNP buffers from being open, if they are lower than this value.

The screen recording would help also to determine if it's _expected_ or not

**Comment by acurrieclark** [comment]
Sorry for the delay, struggling to get a minimal local setup so that I can get a recording for you. Will sort ASAP.

**Comment by shortcuts** [comment]
Hey @acurrieclark no worries, if you have your dotfiles repo where I can reproduce it would be enough for me to investigate

**Comment by shortcuts** [comment]
Hey @acurrieclark, came back to the issue trying to reproduce and I believe as of https://github.com/shortcuts/no-neck-pain.nvim/pull/254, everything seems to behave correctly.

feel free to reopen if you find any issue

**Comment by acurrieclark** [comment]
@shortcuts so sorry, should have come back to you about this. I’ll try with the latest and report back. Thanks for taking the time to look into it.
