### ISSUE TITLE
With the right buffer disabled on vimEnter, text is cut/hidden.

### ISSUE THREAD

**Issue by vinoff** [shortcuts/no-neck-pain.nvim#277]
This is my NoNeckPain config:

```
return {
	"shortcuts/no-neck-pain.nvim",
	config = function()
		require("no-neck-pain").setup({
			autocmds = {
				enableOnVimEnter = true,
				-- enableOnVimEnter = false,
			},
			buffers = {
				right = {
					enabled = false,
				},
			},
		})
	end,
}
```

When using NeoVide, this is what I see when I open a file using neovide (neovide telescope.lua in terminal): 
![noneckpain](https://github.com/shortcuts/no-neck-pain.nvim/assets/90382765/b4a2b1d8-dbeb-4aa5-a773-b20070d75003)

Notice that the text is hidden/cut. If I do something on the file, however, the problem fixes itself. For example, if I go to the bottom of the file by doing G, the text is shown.

Interestingly, I cannot reproduce this on the terminal because my config doesnt make NoNeckTree auto-open there.

**Comment by shortcuts** [comment]
Hey @vinoff, thanks for reporting and using the plugin!

I guess there might be a conflict with Neovide in that case because I have this exact same setup and can't reproduce! I'll take a look ASAP

![Screenshot 2023-12-06 at 12 22 16](https://github.com/shortcuts/no-neck-pain.nvim/assets/20689156/c089502f-fd75-44d1-bfa1-27f18b0808fa)

**Comment by shortcuts** [comment]
Actually I just realized, it's not cut or hidden, you have the right buffer enabled, no?

You can try to add `buffers={right={enabled=false}}` at the root of your config
