### ISSUE TITLE
Wrong buffers disposition upon attempt to exit with unwritten change

### ISSUE THREAD

**Issue by avario-cpu** [shortcuts/no-neck-pain.nvim#376]
Reproduce:

Open any buffer, type --test, or aynthing. Exit buffer without saving.

We get the [wrong_buffer](https://github.com/user-attachments/assets/6ae48ca4-8571-4b5c-9426-dfe142d14b68) disposition after jumping to the error.

This is both with defaults "error jump" nvim behavior or the notify "jump" setting enabled. (In this example, notify, and what I could think as of other plugins having an impact, are disabled).

I'm 90% sure I'm doing something stupid and it's my fault though, I was expecting to find similar issues closed.

P.S. Would love to know how  to have the status bar cover the side buffers too, can't firgure it out.

**Comment by shortcuts** [comment]
Hey, thanks for using the plugin :D

> I'm 90% I'm doing somthing stupid and it's my fault though, I was expecting to find similar issues closed.

I'm not sure because we have a custom behavior when trying to quit nvim with unsaved buffer.

Would you mind letting me know if you can repro by installing the plugin on this branch? https://github.com/shortcuts/no-neck-pain.nvim/tree/feat/winlayout

It's an ongoing feature that should prevent any buffer misplacement, so it might already be fixed there

> P.S. Would love to know how to have the status bar cover the side buffers too, can't firgure it out.

See `:h statusline` you can set the `global` option which will be buffer-based but take the full width

**Comment by avario-cpu** [comment]
> Would you mind letting me know if you can repro by installing the plugin on this branch? https://github.com/shortcuts/no-neck-pain.nvim/tree/feat/winlayout

No sucess cloning doing it the only way  I'm so far accustomed to: lua table w/ Lazy

```
return {
  "shortcuts/no-neck-pain.nvim/tree/feat/winlayout"
}
```

Error from Lazy: clone failed, no such file or dir
